### ISSUE TITLE
Comment 1 for Seikou.

### ISSUE THREAD

**Issue by brmouzinho** [luizaandrade/msfr-git#20]
I guess you could reorganize the line 49 of the lyrics: [click here](https://github.com/luizaandrade/msfr-git/blob/main/lyrics/bohemian-rhapsody-ptx4queens.txt).

**Comment by skonedavid** [comment]
> I guess you could reorganize the line 49 of the lyrics: [click here](https://github.com/luizaandrade/msfr-git/blob/main/lyrics/bohemian-rhapsody-ptx4queens.txt).

**Comment by brmouzinho** [comment]
This is resolved.
